["water_50cl"] = {["name"] = "water_50cl", ["label"] = "Water 50cl", ["weight"] = 500, ["unique"] = true, ["useable"] = true, ["shouldClose"] = true, ["image"] = "water_50cl.png", ["type"] = "item"},
["base_food"] = {["name"] = "base_food", ["label"] = "Base Food", ["weight"] = 0, ["unique"] = true, ["useable"] = true, ["shouldClose"] = true, ["image"] = "base_food.png", ["type"] = "item"},
["base_drink"] = {["name"] = "base_drink", ["label"] = "Base Drink", ["weight"] = 0, ["unique"] = true, ["useable"] = true, ["shouldClose"] = true, ["image"] = "base_drink.png", ["type"] = "item"},
["base_one_hit"] = {["name"] = "base_one_hit", ["label"] = "Base One Hit", ["weight"] = 0, ["unique"] = true, ["useable"] = true, ["shouldClose"] = true, ["image"] = "base_one_hit.png", ["type"] = "item"},
["beer_50cl"] = {["name"] = "beer_50cl", ["label"] = "Beer 50cl", ["weight"] = 550, ["unique"] = true, ["useable"] = true, ["shouldClose"] = true, ["image"] = "beer_50cl.png", ["type"] = "item"},
["burger"] = {["name"] = "burger", ["label"] = 'Burger', ["weight"] = 220, ["unique"] = true, ["useable"] = true, ["shouldClose"] = true, ["image"] = "burger.png", ["type"] = "item"},
["kira_kira_currye"] = {["name"] = "kira_kira_currye", ["label"] = "Curry", ["weight"] = 300, ["unique"] = true, ["useable"] = true, ["shouldClose"] = true, ["image"] = "kira_kira_currye.png", ["type"] = "item"},
["hotdog"] = {["name"] = "hotdog", ["label"] = "Hotdog", ["weight"] = 160, ["unique"] = true, ["useable"] = true, ["shouldClose"] = true, ["image"] = "hotdog.png", ["type"] = "item"},
["nicotine_pouch"] = {["name"] = "nicotine_pouch", ["label"] = "Nicotine Pouch", ["weight"] = 5.0, ["unique"] = true, ["useable"] = true, ["shouldClose"] = true, ["image"] = "nicotine_pouch.png", ["type"] = "item"},

-- Consumables Ingredients
["burger_buns"] = {["name"] = "burger_buns", ["label"] = "Burger Buns", ["weight"] = 30.0, ["unique"] = true, ["image"] = "burger_buns.png", ["type"] = "item"},
["burger_patty"] = {["name"] = "burger_patty", ["label"] = "Burger Patty", ["weight"] = 75.0, ["unique"] = true, ["image"] = "burger_patty.png", ["type"] = "item"},
["mustard"] = {["name"] = "mustard", ["label"] = "Mustard", description = "A splat of mustard to put on your burger.", ["weight"] = 5.0, ["unique"] = true, ["image"] = "mustard.png", ["type"] = "item"},
["ketchup"] = {["name"] = "ketchup", ["label"] = "Ketchup", description = "A splat of ketchup to put on your burger.", ["weight"] = 5.0, ["unique"] = true, ["image"] = "ketchup.png", ["type"] = "item"},
["secret_sauce"] = {["name"] = "secret_sauce", ["label"] = "Secret Sauce", description = "A splat of secret sauce to put on your burger.", ["weight"] = 5.0, ["unique"] = true, ["image"] = "secret_sauce.png", ["type"] = "item"},
["pickles"] = {["name"] = "pickles", ["label"] = "Pickles", description = "A few pickles to put on your burger.", ["weight"] = 25.0, ["unique"] = true, ["image"] = "pickles.png", ["type"] = "item"},
["cheese"] = {["name"] = "cheese", ["label"] = "Cheese", description = "A slice of cheese to put on your burger.", ["weight"] = 25.0, ["unique"] = true, ["image"] = "cheese.png", ["type"] = "item"},
["lettuce"] = {["name"] = "lettuce", ["label"] = "Lettuce", description = "A few leaves of lettuce to put on your burger.", ["weight"] = 25.0, ["unique"] = true, ["image"] = "lettuce.png", ["type"] = "item"},